server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com # eureka 服务端实例名
  client:
    register-with-eureka: false # 不向注册中心注册自己 单机使用
    fetch-registry: false # 表示自己是注册中心，职责就是维护服务实例
    service-url:
      # 单机版Eureka
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群版Eureka
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka/
  server:
    enable-self-preservation: false  # 自我保护机制
    eviction-interval-timer-in-ms: 2000   # client 检测的时间间隔


