CREATE TABLE `payment` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`serial` VARCHAR(200) DEFAULT '' COMMENT '订单序列号',
	PRIMARY KEY(`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

